### ISSUE TITLE
TargetID problem in CustomEditors.cs

### ISSUE THREAD

**Issue by AndyGFX** [Dharengo/SpriterDotNetMecanim#4]
Assets/SpriterDotNetMecanim/Editor/CustomEditors.cs(39,38): error CS1061: Type `object' does not contain a definition for`TargetID' and no extension method `TargetID' of type`object' could be found (are you missing a using directive or an assembly reference?)

O.

**Comment by Dharengo** [comment]
Issue has been fixed, for now.
